package tverd.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;

public class Compra_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.getBuffer().append("sarasitas");
  }
}
