package tverd.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptBalance = new ConceptDescriptorBuilder("tverd.structure.Balance", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9eb5f7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(8295061481379596216L, "productos", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba79188L), true, true, false), new ConceptDescriptorBuilder.Link(8295061481379566206L, "medidas", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba791afL), true, true, false), new ConceptDescriptorBuilder.Link(8295061481379480882L, "clientes", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f648aL), true, true, false), new ConceptDescriptorBuilder.Link(8295061481379041938L, "creditos", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L), true, true, false), new ConceptDescriptorBuilder.Link(8295061481379598452L, "compras", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba80590L), true, true, false)).children(new String[]{"productos", "medidas", "clientes", "creditos", "compras"}, new boolean[]{true, true, true, true, true}).create();
  /*package*/ final ConceptDescriptor myConceptCliente = new ConceptDescriptorBuilder("tverd.structure.Cliente", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f648aL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptClienteBalance = new ConceptDescriptorBuilder("tverd.structure.ClienteBalance", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8295061481379481514L, "dinero")).properties("dinero").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8295061481379481524L, "cliente", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f648aL), false)).references("cliente").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptClienteCredito = new ConceptDescriptorBuilder("tverd.structure.ClienteCredito", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f6d04L)).super_("tverd.structure.ClienteBalance").super_(MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L)).parents("tverd.structure.ClienteBalance").parentIds(MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L)).alias("Credito", "Suma cr\u00e9dito a un cliente").create();
  /*package*/ final ConceptDescriptor myConceptClienteDeuda = new ConceptDescriptorBuilder("tverd.structure.ClienteDeuda", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f6489L)).super_("tverd.structure.ClienteBalance").super_(MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L)).parents("tverd.structure.ClienteBalance").parentIds(MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba64788L)).alias("Deuda", "Registra deuda de un cliente").create();
  /*package*/ final ConceptDescriptor myConceptCompra = new ConceptDescriptorBuilder("tverd.structure.Compra", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba80590L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8295061481379595700L, "cantidad")).properties("cantidad").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8295061481379595692L, "cliente", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77db9f648aL), false), new ConceptDescriptorBuilder.Ref(8295061481379595695L, "medida", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba791afL), false), new ConceptDescriptorBuilder.Ref(8295061481379596107L, "producto", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba79188L), false)).references("cliente", "medida", "producto").alias("Compra", "Una compra realizada por un cliente").create();
  /*package*/ final ConceptDescriptor myConceptMedida = new ConceptDescriptorBuilder("tverd.structure.Medida", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba791afL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8295061481379566027L, "gramos")).properties("gramos").create();
  /*package*/ final ConceptDescriptor myConceptProducto = new ConceptDescriptorBuilder("tverd.structure.Producto", MetaIdFactory.conceptId(0x1f73cc9c8de4b2fL, 0xa1ea262f9788b306L, 0x731dfa77dba79188L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBalance, myConceptCliente, myConceptClienteBalance, myConceptClienteCredito, myConceptClienteDeuda, myConceptCompra, myConceptMedida, myConceptProducto);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0m, conceptFqName)) {
      case 0:
        return myConceptBalance;
      case 1:
        return myConceptCliente;
      case 2:
        return myConceptClienteBalance;
      case 3:
        return myConceptClienteCredito;
      case 4:
        return myConceptClienteDeuda;
      case 5:
        return myConceptCompra;
      case 6:
        return myConceptMedida;
      case 7:
        return myConceptProducto;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0m = new String[]{"tverd.structure.Balance", "tverd.structure.Cliente", "tverd.structure.ClienteBalance", "tverd.structure.ClienteCredito", "tverd.structure.ClienteDeuda", "tverd.structure.Compra", "tverd.structure.Medida", "tverd.structure.Producto"};
}
