package tverd.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Balance_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Balance_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "tverd.structure.Balance";
  }
}
