package tverd.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Balance_BehaviorDescriptor();
      case 3:
        return new ClienteDeuda_BehaviorDescriptor();
      case 1:
        return new Cliente_BehaviorDescriptor();
      case 2:
        return new ClienteCredito_BehaviorDescriptor();
      case 6:
        return new Producto_BehaviorDescriptor();
      case 5:
        return new Medida_BehaviorDescriptor();
      case 4:
        return new Compra_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"tverd.structure.Balance", "tverd.structure.Cliente", "tverd.structure.ClienteCredito", "tverd.structure.ClienteDeuda", "tverd.structure.Compra", "tverd.structure.Medida", "tverd.structure.Producto"};
}
