package tverd.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class ClienteBalance_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ClienteBalance_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "tverd.structure.ClienteBalance";
  }
}
