package tverd.behavior;

/*Generated by MPS */


public class ClienteDeuda_BehaviorDescriptor extends ClienteBalance_BehaviorDescriptor {
  public ClienteDeuda_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "tverd.structure.ClienteDeuda";
  }
}
