package tverd.behavior;

/*Generated by MPS */


public class ClienteCredito_BehaviorDescriptor extends ClienteBalance_BehaviorDescriptor {
  public ClienteCredito_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "tverd.structure.ClienteCredito";
  }
}
