package tverd.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Compra_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Compra_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "tverd.structure.Compra";
  }
}
