package tverd.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Balance_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Cliente_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ClienteCredito_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ClienteDeuda_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Compra_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Medida_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Producto_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"tverd.structure.Balance", "tverd.structure.Cliente", "tverd.structure.ClienteCredito", "tverd.structure.ClienteDeuda", "tverd.structure.Compra", "tverd.structure.Medida", "tverd.structure.Producto"};
}
